name: Sync Active Ads

on:
  schedule:
    # Executar a cada 6 horas: 00:00, 06:00, 12:00, 18:00 UTC
    - cron: '0 */6 * * *'
  workflow_dispatch: # Permitir execução manual

jobs:
  sync-active-ads:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '18'
        cache: 'npm'
        
    - name: Install dependencies
      run: npm ci
      
    - name: Create .env.local
      run: |
        cat > .env.local << EOF
        SUPABASE_URL=${{ secrets.SUPABASE_URL }}
        SUPABASE_ANON_KEY=${{ secrets.SUPABASE_ANON_KEY }}
        SUPABASE_SERVICE_ROLE_KEY=${{ secrets.SUPABASE_SERVICE_ROLE_KEY }}
        META_ACCESS_TOKEN=${{ secrets.META_ACCESS_TOKEN }}
        META_ACCOUNT_ID=${{ secrets.META_ACCOUNT_ID }}
        EOF
        
    - name: Run sync script
      run: node scripts/sync-active-ads.js
      env:
        NODE_ENV: production
        
    - name: Upload logs
      uses: actions/upload-artifact@v4
      if: always()
      with:
        name: sync-logs-${{ github.run_id }}
        path: logs/
        retention-days: 7 